# Basic instance setup
name = "my-first-bjishk"
admin_email = "me@example.com"
port = 3015
base_url = "http://localhost:3015"
notification_key = "random-string-for-coordination"

# My services to monitor (URL is the unique identifier, names auto-fetched from page titles)
[[services]]
url = "https://example.com"
email = "me@example.com"
check_interval = 300

[[services]]
url = "https://example.org"
email = "me@example.com"
check_interval = 120

# Peer instances (just the URLs)
peers = [
  "https://bjishk.example.org"
]

# Email for notifications
[email]
smtp_host = "smtp.gmail.com"
smtp_port = 587
smtp_user = "me@gmail.com"
smtp_pass = "app-password-here"
smtp_from = "me@gmail.com"
smtp_tls = true

# Database path (SQLite)
[database]
path = "./data/bjishk.sqlite"

# Monitoring Configuration
[monitoring]
default_check_interval = 300 # Default check every 5 minutes (in seconds)
retries = 3 # Number of retries before declaring a service as down
retry_delay = 10 # Seconds between retries
peer_check_interval = 60 # Check peer instances every minute (in seconds)

# Web Interface Configuration
[ui]
refresh_interval = 30 # Refresh UI data every 30 seconds 